### ISSUE TITLE
devicemotionのクリックボタンを複数回作動させる

### ISSUE THREAD

**Issue by jibiking** [jibiking/muscle_beat#40]
### 実現したいこと

indexページにある上記クリックイベントを、スマホでクリックするたびに動作させたい。

### 該当コード

- [view/beats/index](https://github.com/jibiking/muscle_beat/blob/main/app/views/beats/index.html.erb)
- [javascript/packs/common/common.js](https://github.com/jibiking/muscle_beat/blob/main/app/javascript/packs/common/common.js)

### 現状＆試したこと

1. スマホで上記クリックイベントが１度しか動作せず、再度動作させるには一定時間置く必要がある。
2. PCでは複数回動作可能（おそらくdevicemotionに干渉してないから）
3. 他の[devicemotionを使用しているサイト](https://hajimete.org/jquery-devicemotion-ios13)も同様に１度しかクリックをできないことから、devicemotionの仕様上の仕組みなのではないかと考えました。

### 考察
上記３のように考えましたが、いまいち決定打に足る資料が見つからなかったので、ご相談させていただきました。
解決方法や参考サイトなどをご教授いただければと思います。
よろしくお願いいたします。

### 参考記事

- [[公式](https://developer.mozilla.org/ja/docs/Web/API/Window/devicemotion_event)](https://developer.mozilla.org/ja/docs/Web/API/Window/devicemotion_event)
- [[参考サイト](https://moriokalab.com/news/63)](https://moriokalab.com/news/63)

**Comment by MrFuku** [comment]
devicemotionのことはよくわかりませんが、こちらの記事を見た感じ繰り返しイベントは実行されると思います。
検証方法に不備がないかを調査してください。
検証はシンプルかつ極端な挙動を試すのが良いです。

https://neos21.net/blog/2017/10/21-02.html

> 大抵は0.001秒みたいな物凄い勢いで繰り返し呼び出されるので、ログ出力やパワーが必要な処理を高速で何度も呼び出さないように注意したい。

**Comment by jibiking** [comment]
devicemotionイベントのrequestPermition（加速度センサーの使用許可をポップアップでスマホに表示する仕組み）は１度しか発火させられない。
設定からページキャッシュを削除すれば再度発火させられる。
