### ISSUE TITLE
JSファイルの移行

### ISSUE THREAD

**Issue by jibiking** [jibiking/muscle_beat#46]
### 実現したいこと

packs以下のjsファイル内で、erbタグで動的にファイル等の読み込みを行いたい。

### 該当コード

- [view/beats/show](https://github.com/jibiking/muscle_beat/blob/main/app/views/beats/show.html.erb)

### 現状＆試したこと

1. 現状、phina.jsをviewのscriptタグ内にベタ書きして、その中でerbタグで動的にファイル等を読み込んでいます。この記述をpacks以下に移行したいと考えているのですが、
2. 1の記述をpack内の.jsファイルに入れると、erbの読み込みができなくなる。
3. 2のerbを読み込むために、.js.erbに拡張子を変更すると、javascript_pack_tagでの読み込みができなくなってしまう。
上記のようになってしまい、解決への糸口が掴めずにいます。

### 考察
- javascript_pack_tagの他に、.js.erbファイルを読み込む用のタグがある？と考えましたが発見に至ってません。
- jsでerbを使用する際はviewにベタ書きしかない？と考えましたが、いまいちその決定打となる資料を発見できていません。

解決方法や参考サイトなどをご教授いただければと思います。
よろしくお願いいたします。

### 参考

- [[.js.erbについて](https://zenn.dev/swata_dev/articles/c51f3b781c916d)](https://zenn.dev/swata_dev/articles/c51f3b781c916d)

**Comment by MrFuku** [comment]
> packs以下のjsファイル内で、erbタグで動的にファイル等の読み込みを行いたい。

それはできません。
erbはリクエスト時にコンパイルしますが、`packs`は事前コンパイルです

**Comment by jibiking** [comment]
上記回答から、現状のままbeats#showにphina.jsを記載し、erbタグで同的読み込みを行う。

close #46
